### ISSUE TITLE
BPearl Point time calculation

### ISSUE THREAD

**Issue by tomarsnap** [RoboSense-LiDAR/rs_driver#1]
Hey,

Is it possible to add the point time calculation to the driver side for the BPearl lidar? The functionality is depicted on the user manual, but it doesn't seem like the driver does the calculation at the moment. Other lidar manufacturers seem to have implemented this by sending the offset time with each point.

So each point would have
```
x:
y:
z:
intensity:
time:
```

The time field would be the offset from the header time stamp, as shown in the Appendix A Point Time Calculate, Table A - 1: Time Offset for each Channel in single Return Mode of the RS-Bpearl_User_Guide.pdf

**Comment by tomarsnap** [comment]
@quchunlei @CrazyTomX @jdwu2019 @steelwu 
Any development on this?

**Comment by CrazyTomX** [comment]
Thanks for your advice!  Since the point type is template now, we are considering add the XYZIT type support in Version 1.2.

**Comment by tomarsnap** [comment]
Hey, have you decided on this yet? The feature is quite important for autonomous driving and would allow for deeper integration of the RoboSense products into real applications. Hoping you get this implemented!

**Comment by CrazyTomX** [comment]
> Hey, have you decided on this yet? The feature is quite important for autonomous driving and would allow for deeper integration of the RoboSense products into real applications. Hoping you get this implemented!

Yes, we have added the timestamp & ring - id support in our point type. Now the decoder can auto detect which variable the point struct has and then set the value.  The v1.2 is going to be released on September.

**Comment by tomarsnap** [comment]
Okay that's great! So it does the point time calculation if the PointXYZIRT type is selected from configuration?

**Comment by CrazyTomX** [comment]
> Okay that's great! So it does the point time calculation if the PointXYZIRT type is selected from configuration?

Not by configuration. As I said, the decoder can detect whether a target variable is in your struct automatically. For example, you have a point type:
PointT
{
double x;
double y;
double z;
}
Then the decoder will only set the x, y, z value to your point type. 
If your point type is:
PointT
{
double x;
double y;
double z;
double intensity;
double timestamp;
int ring;
int anything_else;
}
The decoder will set x,y,z,intensity,timestamp,ring value to your point type.
The only thing you need to pay attention is that the variable name must obey the rules,(x, y, z, intensity, timestamp, ring ),  other wise the variable can not be detected and can not be set value correctly.
