### ISSUE TITLE
Wrong resolution (constant) for RS16

### ISSUE THREAD

**Issue by nsch0e** [RoboSense-LiDAR/rs_driver#10]
Hi,

I'm using an RS16 lidar with the rslidar_sdk in ROS1. All distances are half of what they should be. Using the old driver ros_rslidar everything is as it should be and the driver says that the lidar operates at 1cm resolution instead of the configured 0.5cm.

I have not figured out why the lidar doesnt operate at 0.5cm (wrong FW?) but at least the old driver compensates for that.

New driver seems to expect that all lidars can provide higher resolution (see value in file below).

https://github.com/RoboSense-LiDAR/rs_driver/blob/e9d8d761455b53b8276a10dc4831501e09557c74/src/rs_driver/driver/decoder/decoder_base.hpp#L62

For now I manually changed the file but I think there should be a check in the driver which adjusts the resolution.
Also can you confirm that a FW update is needed for 0.5cm resolution?

Thanks!

**Comment by HaoQChen** [comment]
Hi, nsch0e

RSLidar's distance resolution has been changed to 0.5cm for a long time, rs_driver is not compatible with the old version. Compatibility need a lot code which will lead to unnecessary code redundancy.

You can change `RS_DIS_RESOLUTION` to 0.01 if you are using a lidar with resolution of 1cm. 

Sorry for the incompatibility

**Comment by nsch0e** [comment]
Thank you for your fast answer. I understand that you don't want to support old versions.
Perhaps you could display a warning nevertheless.

I think these lines are kind of checking the firmware in the old driver. The values don't match current UserGuide 4.1 but perhaps it's a start.
https://github.com/RoboSense-LiDAR/ros_rslidar/blob/726eacca94560c4e40e679b899f2b2c43b8a229f/rslidar_pointcloud/src/rawdata.cc#L355
