### ISSUE TITLE
RS-LiDAR-M1 LiDAR support

### ISSUE THREAD

**Issue by praveenputhettu** [RoboSense-LiDAR/rs_driver#13]
Will this driver works for RS-LiDAR-M1?

**Comment by HaoQChen** [comment]
Please contant armin.mu@robosense.cn to check your lidar's version. 

rs_driver does not support some early M1

**Comment by praveenputhettu** [comment]
Thank you HaoQChen.

**Comment by praveenputhettu** [comment]
I think this driver doesnt support LiDAR M1 (B2, Sample).

**Comment by Rinntrah** [comment]
Which driver supports  LiDAR M1 (B2, Sample)?
