### ISSUE TITLE
Data loss experienced when connecting two Robosense Lidar.

### ISSUE THREAD

**Issue by praveenputhettu** [RoboSense-LiDAR/rs_driver#14]
I had connected two Robosense Lidar through a hub to an Ethernet port. 
But i am not getting datas from it at the same time. 
Is there any way to resolve this?

**Comment by HaoQChen** [comment]
You should set this two lidar with different IP, DIFOP and MSOP port

contact armin.mu@robosense.cn

He will help you with that

**Comment by ju-mingyue** [comment]
Hello, I am very happy to see the relevant information on Github,
My current project needs to use two laser signals, the first is the signal released by the lidar itself (scan1), and the second is the laser radar signal (scan2) released by the D435 after conversion. How can I make this The two signals are merged into one (scan) and released to AMCL?

**Comment by HaoQChen** [comment]
> Hello, I am very happy to see the relevant information on Github,
> My current project needs to use two laser signals, the first is the signal released by the lidar itself (scan1), and the second is the laser radar signal (scan2) released by the D435 after conversion. How can I make this The two signals are merged into one (scan) and released to AMCL?

It is not relevant....

your problem is not the sensor's problem, you need to learn about how to calibrate two sensor's relative position
