### ISSUE TITLE
Difop Packet Corruption with RS-BPearl

### ISSUE THREAD

**Issue by kvern-code** [RoboSense-LiDAR/rs_driver#15]
I have a typical set-up for analyzing the difop packet from the RS-BPearl unit. This the callback function which I have registered with the driver. 

```
static void difopCallback(const PacketMsg &difop_msg)
{ 
  std::unique_lock<std::mutex> lk_difop (mtx_dfp, std::try_to_lock);
  if (lk_difop.owns_lock() == true)
  {
    g_dpkt_ptr = (RSBPDifopPkt*)difop_msg.packet.data(); //pointer holding all of difop message

    // lk_difop.unlock();
  }
  else
  {
   //wait until we can update global difop packet
  }
}
```

Then I have a getter function which gets the newest global difop packet. This function simply locks the mutex, copies the global difop packet into a local copy then performs some analysis in `difopProcess`.
```
int getDiagnostics(gcv_packet *gcv_udp)
{
  std::unique_lock<std::mutex> lk_difop (mtx_dfp, std::try_to_lock);
  if (lk_difop.owns_lock() == true)
  {
    RSBPDifopPkt l_dpkt;
    memcpy(&l_dpkt, g_dpkt_ptr, sizeof(*g_dpkt_ptr));
    difopProcess(&l_dpkt, gcv_udp);

    lk_difop.unlock();
    return 0;
  }
  else
  {
    return -1;
  }
}
```

I have noticed through my analysis that the difop packet is not properly working. It enters my program corrupted or shifted to some extent. I discovered this by printing out certain parts of the packet, namely RPM, and manc_err_1 and manc_err_2 before and after copying for the local and global versions. The copying is clean and works but the packet holds values which are impossible. The sensor functions fine and I get point cloud data no problem. I have been working with these sensors for a few months now and have just discovered this difop issue. Any ideas or fixes would be greatly appreciated. 

I am confident the mutex locking and unlocking is not the problem for the record. I am getting bad data in for some reason.

**Comment by kvern-code** [comment]
UPDATE:
The behavior is fixed when compiling in CMAKE DEBUG mode. Then, when I recompile in CMAKE RELEASE mode the issue is present. Something is being optimized away in the Cmake process and I do not know what.

**Comment by HaoQChen** [comment]
You should copy data to `g_dpkt_ptr` in `difopCallback`

in your case, `g_dpkt_ptr` just point to a temporary address, which will reset no matter you lock or not

you need to lock  the address, not the `g_dpkt_ptr``

**Comment by kvern-code** [comment]
Oh duh... I fixed with

`   
memcpy(&g_dpkt, difop_msg.packet.data(), sizeof(g_dpkt));
`    
where g_dpkt is not a pointer but is a RSBPDifopPkt class defined globally. Thanks for the support.
