### ISSUE TITLE
Point Cloud Lag

### ISSUE THREAD

**Issue by kvern-code** [RoboSense-LiDAR/rs_driver#16]
Hello, I will try to make this a brief as possible. I have the following set up for a RS-BPearl unit.

Thread 1: Communication server (simple UDP)
Thread 2: Robosense driver

I start the driver in the usual way in my main loop. 

```
void initLidarDriver(RSDriverParam &param)
{
	param.wait_for_difop = false;
	param.lidar_type = param.strToLidarType("RSBP"); //RoboSense BPearl
	param.input_param.msop_port = MSOP_PORT;   //MSOP port number
	param.input_param.difop_port = DIFOP_PORT; //difop port number 
    driver.regExceptionCallback(exceptionCallback); //Register the exception callback function into the driver
    driver.regRecvCallback(pointCloudCallback);     //Register the point cloud callback function into the driver
    driver.regRecvCallback(difopCallback);         //Register the lidar diagnostics callback function into the driver
    if (!driver.init(param)) //Call the init function and pass the parameter
    {
		RS_ERROR << "Driver Initialize Error" << RS_REND;
		return;
    }

    driver.start(); //Start the driver thread
    RS_INFO << "Starting Cloud Logger" << RS_REND;
}
```
My callback updates a global point cloud pointer called g_scan_cloud. 
```
static void pointCloudCallback(const PointCloudMsg<pcl::PointXYZI> &msg) 
{
	std::unique_lock<std::mutex> lk (mtx, std::try_to_lock);
	if (lk.owns_lock())
	{
		if (msg.height*msg.width == 57600) //check for full message
		{
			//Conversion to pcl type cloud from robosense lidar message
			g_scan_cloud->is_dense = false;
			g_scan_cloud->points.assign(msg.point_cloud_ptr->begin(), msg.point_cloud_ptr->end());
			g_scan_cloud->height = msg.height;
			g_scan_cloud->width = msg.width;
			std::cout << "updated global\n";
		}
		lk.unlock();
	}
	else
	{
		std::cout << "NO LOCK ON CALLBACK\n";
	}
}
```

Then I have a getter function that is called by my UDP server thread:

```
int getData(gcv_packet *gcv_udp)
{
	std::unique_lock<std::mutex> lk (mtx, std::try_to_lock);
	if (lk.owns_lock())
	{
		pcl::PointCloud<pcl::PointXYZI>::Ptr l_scan_cloud (new pcl::PointCloud<pcl::PointXYZI>);
		*l_scan_cloud = *g_scan_cloud; //data copy not a ptr copy which is what we want

		if (process(l_scan_cloud, gcv_udp) != 0)
		{
			return -1;
		}
		else
		{
			return 0;
		}
	}
	else
	{
		std::cout << "NO LOCK ON GETTER\n";
		return -1;
	}
}
```

So the idea is that my global cloud is always being updated by the callback, then when I need to make a calculation I call my getter, it locks the data, copies that global, then unlocks the data, and passes the local to be processed. However, there is a severe lag of about 15-30 seconds in the response of the program. For example, if I call getData() once a second, the viewer should be updated with a new point cloud once a second. However, when I call the process, the viewer is updated with a point cloud from anywhere from 15-30 seconds ago. It is like there is a First in First Out queue instead of a Last In First Out queue. To be clear, the viewer isn't lagging but it is just displaying a cloud from a long time ago. I even tried starting my program, letting it run for a moment, then unplugging my sensor. It reports TIMEOUT errors, but I still get point clouds in. Very confusing!

Finally, here is the server main loop:
```
void * UDP_Server::sendLoop() 
{
	int16_t buffer[UDP_PACKET_SIZE];
	int sfd, n; 
	gcv_packet gcv_udp;
	socklen_t len;
	struct sockaddr_in receiver_addr; 

	while(true) 
	{
		std::chrono::high_resolution_clock::time_point start_time = std::chrono::high_resolution_clock::now();

		len = sizeof(receiver_addr);
		sfd = initSocket(sfd);
		bindSocket(sfd, &receiver_addr); 

		// get data
		getData(&gcv_udp);

		//print data for debug
		printMsg(&gcv_udp);

		memcpy(&buffer[0], &gcv_udp, sizeof(gcv_udp)); //fill buffer

		sendto(sfd, buffer, sizeof(buffer),
			MSG_CONFIRM, (const struct sockaddr *) &receiver_addr, len);

		resetSocket(sfd, &gcv_udp, &receiver_addr);
		
		std::cout << "\n\n";
		std::chrono::high_resolution_clock::time_point end_time = std::chrono::high_resolution_clock::now();
		std::chrono::duration<double, std::milli> time_span = end_time - start_time;
		std::this_thread::sleep_for(std::chrono::milliseconds(1000)-time_span); //sets loop frequency at 1Hz
	}
	return 0;
}
```

Let me know if you need more information, this issue is frustrating me greatly.

**Comment by kvern-code** [comment]
Hello, even if I circumvent the entire UDP thread, and call process() inside of my callback function while the global cloud is still locked, I experience the same viewer delay. This used to not be an issue I am not sure what is going on.

**Comment by kvern-code** [comment]
Hello, I checked the sensor functionality in RS-View and the point cloud reacts quickly without lag. I analyzed the packet rate in wireshark and the sensor is sending at 10Hz. If I reduce my callback to a simple `std::cout << "hit callback" << std::endl;` I get a print statement at about 1Hz. If I do the same in the difopCallback() function, I get a message at about 10Hz. So, something is slowing down my pointCloudCallback() in the driver side somewhere.

**Comment by HaoQChen** [comment]
```cpp
int getData(gcv_packet *gcv_udp)
{
  {
    std::unique_lock<std::mutex> lk (mtx, std::try_to_lock);

    pcl::PointCloud<pcl::PointXYZI>::Ptr l_scan_cloud (new pcl::PointCloud<pcl::PointXYZI>);
    *l_scan_cloud = *g_scan_cloud; //data copy not a ptr copy which is what we want
  }
  

  if (process(l_scan_cloud, gcv_udp) != 0)
  {
    return -1;
  }
  else
  {
    return 0;
  }
}
```

your way to copy g_scan_cloud will occupy mutex until process finish

I think your process need 30 seconds?

**Comment by kvern-code** [comment]
Good point I have moved my `lk.unlock()` but the behavior is still the same. `process()` takes about 1 second. 

I reduced my code to just the `pointCloudCallback()` function. Even with only the driver callback function, no process or server, I get calls to my callback at 1Hz. 

Take a look at this image. For the top portion the sensor was plugged in. Every time callback is called I print updated global. After about 10 seconds I unplug the sensor power. You can see that I immediately get timeout errors which is good. However, I still get calls to my global as if there are clouds stored in some buffer somewhere, which is bad. I hope this shows the lagging behavior of the driver. We can see it only lags for the point cloud data, and not for the difop or exception callback.  
 
![image](https://user-images.githubusercontent.com/77743560/123996999-e9c49700-d99d-11eb-85dc-98d0f8ce363c.png)

**Comment by HaoQChen** [comment]
> Good point I have moved my `lk.unlock()` but the behavior is still the same. `process()` takes about 1 second.
> 
> I reduced my code to just the `pointCloudCallback()` function. Even with only the driver callback function, no process or server, I get calls to my callback at 1Hz.
> 
> Take a look at this image. For the top portion the sensor was plugged in. Every time callback is called I print updated global. After about 10 seconds I unplug the sensor power. You can see that I immediately get timeout errors which is good. However, I still get calls to my global as if there are clouds stored in some buffer somewhere, which is bad. I hope this shows the lagging behavior of the driver. We can see it only lags for the point cloud data, and not for the difop or exception callback.
> 
> ![image](https://user-images.githubusercontent.com/77743560/123996999-e9c49700-d99d-11eb-85dc-98d0f8ce363c.png)

How about your computer's environment and configuration ?

could you send me a pcap file recorded with `wireshark`  or something, 10 seconds is OK. My e-mail is hqchen@robosense.cn

your code is clone from master branch?

**Comment by kvern-code** [comment]
I am running Ubuntu 20.04 on an Intel 8365U. I am using RS driver version 1.3.0. I have sent you the pcap and also tried to attach it here. 
[rs_bpearl_output.pcap.gz](https://github.com/RoboSense-LiDAR/rs_driver/files/6747471/rs_bpearl_output.pcap.gz)

**Comment by HaoQChen** [comment]
Could you use pointcloud with [rs_driver_viewer](https://github.com/RoboSense-LiDAR/rs_driver/blob/main/doc/howto/how_to_use_rs_driver_viewer.md) ?

I can show pointcloud normally with your pcap, it means lidar is good

I dont think `192.168.1.254`  is a good IP for your computer, it is usually used as a gateway

you can change to `192.168.1.102` maybe

![image](https://user-images.githubusercontent.com/13584792/124129162-179a0080-dab0-11eb-9b1e-0b398adf5518.png)

and check your msop port, it should be 2370 and difop should be 8310

**Comment by kvern-code** [comment]
The RS_View in Windows works perfectly fine. Port numbers are correct. I will try changing the IP addresses and report back.

**Comment by HaoQChen** [comment]
` rs_driver_viewer`  is a part of `rs_driver`, you could try that too

**Comment by HaoQChen** [comment]
or build online demo, see if it is ok

![image](https://user-images.githubusercontent.com/13584792/124129933-d7874d80-dab0-11eb-91bc-57d6f7921580.png)


if demo is ok, some bug in your code
if demo is not ok, some bug in rs_driver

**Comment by kvern-code** [comment]
Okay I ran the demo_online and it looks like I am getting point cloud messages at 10Hz. I will further investigate my code. Thanks for the help. I will keep this issue open until I post my fix, if that is okay.

Changing the IP had no effect.

**Comment by kvern-code** [comment]
I am so mad... Somehow my cmake was defaulting to a Debug build. I switched to Release and it runs perfectly. 

Thank you for your help.

COMPILE IN RELEASE MODE

**Comment by HaoQChen** [comment]
upou
