### ISSUE TITLE
i find the coordinate is different between Rsview software and the project, am i right?

### ISSUE THREAD

**Issue by jiqirenno1** [RoboSense-LiDAR/rs_driver#2]
the coordinate of Rsview software is  y-axis faces straight ahead,
while the coordinate of the rs_driver project is x-axis faces straight ahead,

**Comment by HaoQChen** [comment]
yes, you are right. Sorry to make you feel confused

**Comment by jiqirenno1** [comment]
> yes, you are right. Sorry to make you feel confused

thanks!
