### ISSUE TITLE
Undocumented decoders parameters

### ISSUE THREAD

**Issue by simulacrus** [RoboSense-LiDAR/rs_driver#26]
The https://github.com/RoboSense-LiDAR/rs_driver/blob/1ed9b29388742e01e6652903838a45dd3e5d2cbf/src/rs_driver/driver/decoder/decoder_factory.hpp  file describes the parameters for decoding packets from different lidars. I have questions for:
1.ret_param.RX, ret_param.RY, ret_param.RZ
2. ret_param.DSR_TOFFSET

**Comment by simulacrus** [comment]
Also of interest is the "Zero angle offset" field in the difop packet For some reason, in my case, it always returns the same value and the visible rotation of the scan

**Comment by HaoQChen** [comment]
these are the intrinsic parameters of the lidar
