### ISSUE TITLE
pointCloudCallback(const PointCloudMsg<PointXYZI> &msg)  问题咨询

### ISSUE THREAD

**Issue by ywfwyht** [RoboSense-LiDAR/rs_driver#27]
User can make a copy of the message and process it in another thread. Or user can add some quick operations such like ros publish in the callback function.

void pointCloudCallback(const PointCloudMsg<PointXYZI> &msg)
{
  RS_MSG << "msg: " << msg.seq << " point cloud size: " << msg.point_cloud_ptr->size() << RS_REND;
}

1、怎么将const PointCloudMsg<PointXYZI> &msg  通过ros 发布出去？麻烦示例一下谢谢
2、如何将const PointCloudMsg<PointXYZI> &msg 转换成PCL数据格式？

**Comment by suanli** [comment]
ros用https://github.com/RoboSense-LiDAR/rslidar_sdk这个驱动
pcl格式参考tool下面的[rs_driver_viewer.cpp](https://github.com/RoboSense-LiDAR/rs_driver/blob/main/tool/rs_driver_viewer.cpp)
