### ISSUE TITLE
使用rs_driver解析pcap时出现ERRCODE_NODIFOPRECV，该如何解决呢

### ISSUE THREAD

**Issue by natsume7** [RoboSense-LiDAR/rs_driver#3]

**Comment by HaoQChen** [comment]
你可以先检测一下difop的端口号是否设置正确，驱动中有一个`input_param.difop_port`的参数需要设置。

**Comment by natsume7** [comment]
> 你可以先检测一下difop的端口号是否设置正确，驱动中有一个`input_param.difop_port`的参数需要设置。
difop用的是默认的param.input_param.difop_port = 7788，测试用的是rs80，工程代码中直接连激光雷达解析点云数据是正常的，但用rsview录的pcap解析是就会报错ERRCODE_NODIFOPRECV

**Comment by HaoQChen** [comment]
您可以用wireshark打开这个pcap，查看里面是否有7788的UDP包，可以使用`udp.port==7788`这样的filter

![image](https://user-images.githubusercontent.com/13584792/100714962-794a9d00-33f1-11eb-8c7c-80df66e1d1ab.png)

如果确认没有的话，有可能就是RSView录包设置的问题了。我们建议您使用Wireshark这种相对专业的录包工具，RSView录包只是一个辅助功能，维护不够及时

**Comment by natsume7** [comment]
> 您可以用wireshark打开这个pcap，查看里面是否有7788的UDP包，可以使用`udp.port==7788`这样的filter
> 
> ![image](https://user-images.githubusercontent.com/13584792/100714962-794a9d00-33f1-11eb-8c7c-80df66e1d1ab.png)
> 
> 如果确认没有的话，有可能就是RSView录包设置的问题了。我们建议您使用Wireshark这种相对专业的录包工具，RSView录包只是一个辅助功能，维护不够及时

用wireshark录包就可以了，谢谢
