### ISSUE TITLE
ERRCODE_PKTBUFOVERFLOW

### ISSUE THREAD

**Issue by natsume7** [RoboSense-LiDAR/rs_driver#4]
在项目工程中调用rs_driver解析pcap为点云数据时，遇到报ERRCODE_PKTBUFOVERFLOW时，该如何处理阿

**Comment by HaoQChen** [comment]
驱动里面有这样的两个线程：

1. 负责从pcap里获取MSOP包
2. 将原始的UDP包解析为点云数据。

在这两个线程之间有一个队列进行数据缓存，出现这个问题是因为超过缓存限制了。

请检查您是否在`pointCloudCallback`进行了太多的处理，`pointCloudCallback`这个函数是在第2个线程中进行的。如果您的操作太多，建议您在`pointCloudCallback`中仅做点云获取，然后新建一个线程进行数据处理

**Comment by natsume7** [comment]
> 驱动里面有这样的两个线程：
> 
>     1. 负责从pcap里获取MSOP包
> 
>     2. 将原始的UDP包解析为点云数据。
> 
> 
> 在这两个线程之间有一个队列进行数据缓存，出现这个问题是因为超过缓存限制了。
> 
> 请检查您是否在`pointCloudCallback`进行了太多的处理，`pointCloudCallback`这个函数是在第2个线程中进行的。如果您的操作太多，建议您在`pointCloudCallback`中仅做点云获取，然后新建一个线程进行数据处理

恩，解决了谢谢：）

**Comment by flashlau** [comment]
Thanks! Do not write pcd file here! :P
