### ISSUE TITLE
Error about pthread while cmake demo

### ISSUE THREAD

**Issue by FishInWave** [RoboSense-LiDAR/rs_driver#5]
When compiling the demo with command:`cmake -DCOMPILE_DEMOS=ON ..`，an error occurs as: `/usr/bin/ld: CMakeFiles/demo_pcap.dir/demo_pcap.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5`

And this error can be solved by fixing the CMakeLists.txt in demo through adding `-lpthread` in traget_link_libraries,like:
`target_link_libraries(demo_online
                    ${EXTERNAL_LIBS} -lpthread      
)
`
`
target_link_libraries(demo_pcap
                ${EXTERNAL_LIBS} -lpthread     
)`

**Comment by CrazyTomX** [comment]
Hi,
  Thanks for your message! We have found out this problem yet and it may occurs on some of machines which can not link to pthread automatically. We will add the explicit link in the next version.
