### ISSUE TITLE
How to dump pcap file of pointcloud

### ISSUE THREAD

**Issue by haige-algo** [RoboSense-LiDAR/rs_driver#6]
thanks for your great job. I got how to online connect RS16 and how to load local pcap file.

But, I can not found the API to dump the pcap file, please help me, thanks a lot !

**Comment by CrazyTomX** [comment]
Hi,
 We highly suggest you to use WireShark (a third party tool) to dump pcap file.

**Comment by haige-algo** [comment]
@CrazyTomX , thanks for your suggestion.
I want to record point cloud data without PCL and ROS library, so I think the .pcap file is the best method. WireShark only for test, not works for my request.

**Comment by HaoQChen** [comment]
according to [WiKi](https://en.wikipedia.org/wiki/Pcap)

Or command line tool [tcpdump](https://www.tcpdump.org/manpages/tcpdump.1.html), it  works on most Unix-like operating systems?  `WireShark` will crash sometime when recording big pcap(up to 10G) as we know.

Or CPP tool:
+ `libpcap` for Unix-like operating systems
+ `Npcap` for Windows

**Comment by haige-algo** [comment]
@HaoQChen Thanks, I will test.

**Comment by HaoQChen** [comment]
You can start  a terminal from your code and start the tcpdump in the terminal. We have try them both, this is the most simple way
