### ISSUE TITLE
how to config two robosense-lidars?

### ISSUE THREAD

**Issue by jiqirenno1** [RoboSense-LiDAR/rs_driver#7]
i have two robosense-lidars,  how to connect two lidars to nvidia-tx2 ?  and how to get the data from different id or sth else?

**Comment by HaoQChen** [comment]
Hi there

1. You can use a router or two NICs
2. You need to change lidars' IP and UDP port with RSView
3. You need to new two `LidarDriver` Objests and init them with different `RSDriverParam`  as demo
