### ISSUE TITLE
Can I use 'param.decoder_param.transform_param '  on  online data to transform coordinate ?

### ISSUE THREAD

**Issue by jiqirenno1** [RoboSense-LiDAR/rs_driver#8]

**Comment by jiqirenno1** [comment]
I want to visualize two online lidars,  can I use 'param.decoder_param.transform_param ' on online data to position different lidar on different origin position

**Comment by HaoQChen** [comment]
of course, `decoder_param.transform_param` just multiply a rotation matrix after point is decoded

Please refer to 

 `DecoderRS32<T_Point>::decodeMsopPkt` 

`this->transformPoint(x, y, z);`

`DecoderBase<T_Point>::transformPoint(float& x, float& y, float& z)`

**Comment by jiqirenno1** [comment]
when the ```DecoderRS32<T_Point>::decodeMsopPkt```  was called,  before ```driver.regRecvCallback(pointCloudCallback);``` or I should write the decode in ```pointCloudCallback``` function ?

**Comment by HaoQChen** [comment]
It is called automatically when UDP data come in, and put the pointcloud to your `pointCloudCallback`

We recommend you take some time to read the code if you are going to use it

**Comment by jiqirenno1** [comment]
I see ```lidar_decoder_ptr_ = DecoderFactory<T_Point>::createDecoder(driver_param_)```  when LidarDriver init, but I can not find when ```DecoderRS32<T_Point>::decodeMsopPkt``` function was called,  help me.

**Comment by HaoQChen** [comment]
Hi there

`DecoderRS32<T_Point>::decodeMsopPkt` is called in base class function `DecoderBase<T_Point>::processMsopPkt`, it is a C++ `virtual` functiol

and `processMsopPkt` is call in `LidarDriverImpl<T_Point>::processMsop()`

when you new a `LidarDriver<PointXYZI>` object and `start` it, a `Input` object which used to get data from pcap and socket with some thread is created. When data get, the thread `Input::getMsopPacket()` will call `msop_cb_`

`LidarDriverImpl<T_Point>::msopCallback` is emplace back to `Input->msop_cb_`  in `LidarDriverImpl<T_Point>::init` and as you can see,  `LidarDriverImpl<T_Point>::processMsop()` is push to a thread pool and execute when pool is free

your callback register to LidarDriverImpl is call in `LidarDriverImpl<T_Point>::processMsop()`

**Comment by jiqirenno1** [comment]
Thanks !

**Comment by HaoQChen** [comment]
You are welcome~~
